version: '3'
services:
  mysql:
    image: 154199226033.dkr.ecr.ap-northeast-1.amazonaws.com/first-docker-mysql
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql
    env_file: ./mysql/mysql.env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf:/etc/mysql/conf.d/:ro
      - mysqldata:/var/lib/mysql
    networks:
      - default
  app:
    image: 154199226033.dkr.ecr.ap-northeast-1.amazonaws.com/first-docker
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: app
    env_file: ./app.env
    environment:
      - TZ=Asia/Tokyo
      - DEBUG=app:*
      - CHOKIDAR_USEPOLLING=true
    tty: true
    ports:
      - '80:80'
      - '3000:3000'
      - '3001:3001'
    volumes:
      - ./src:/app
    working_dir: /app
    command: >
      bash -c "npm install &&
      npm start"
    networks:
      - default
    depends_on:
      - mysql
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 4096M
networks:
  default:
# コンテナが削除されてもデータが消えずに保持される
volumes:
  mysqldata:
